# Generated by Django 3.2.8 on 2021-10-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museshare_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicproject',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='musicproject',
            name='tags',
            field=models.CharField(default='Genre tags', max_length=70),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='needs',
            field=models.CharField(default='', max_length=70, verbose_name='Current project needs'),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Project completed'),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='title',
            field=models.CharField(default='', max_length=70, verbose_name='Project title'),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='upload',
            field=models.FileField(upload_to='uploads/', verbose_name='Project audio file'),
        ),
    ]
