# Generated by Django 3.2.8 on 2021-10-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museshare_app', '0002_auto_20211023_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicproject',
            name='tags',
            field=models.CharField(max_length=70, verbose_name='Genre tags'),
        ),
    ]
