# Generated by Django 3.2.8 on 2021-10-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museshare_app', '0003_alter_musicproject_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a musical genre (e.g. Heavy Metal)', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='musicproject',
            name='needs',
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='tags',
            field=models.CharField(max_length=70, verbose_name='Identifier tags'),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='title',
            field=models.CharField(default='', max_length=70, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='upload',
            field=models.FileField(upload_to='uploads/', verbose_name='Audio file'),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this song', to='museshare_app.Genre'),
        ),
    ]
